name: "Auto Assignees"
on:
  pull_request:
    types: [opened, ready_for_review, edited]

jobs:
  register-assignee:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
